### ISSUE TITLE
Error: Could not detect license

### ISSUE THREAD

**Issue by josh-hemphill** [cbhq/semantic-release-license#3]
I have a basic MIT license in my repo root, I'm not sure why it's happening.

It is a Deno based repo, that only installs Node in the action to run semantic-release.

Repo: https://github.com/josh-hemphill/maxminddb-deno
Logs: https://github.com/josh-hemphill/maxminddb-deno/runs/2083445258

**Comment by gempain** [comment]
Your license is missing the `MIT License` header. See the [license](https://github.com/cbhq/semantic-release-license/blob/latest/LICENSE) of this repo and how MIT is [detected](https://github.com/cbhq/semantic-release-license/blob/latest/src/detect-license.ts).
